version: '3.7'

services:
    postgres:
        image: postgres:13.4-alpine
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: db
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - /opt/astra50/postgres/data:/var/lib/postgresql/data

    keycloak:
        image: jboss/keycloak:15.0.1
        command: [ "-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled" ]
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_USER: db
            DB_SCHEMA: public
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            KEYCLOAK_USER: ${KEYCLOAK_USER}
            KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
            PROXY_ADDRESS_FORWARDING: 'true'
        networks:
            - default
            - traefik
        deploy:
            update_config:
                order: stop-first
                failure_action: rollback
                parallelism: 1
                delay: 5s
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.astra50-keycloak.rule=Host(`auth.astra50.ru`)"
                - "traefik.http.routers.astra50-keycloak.entrypoints=websecure"
                - "traefik.http.routers.astra50-keycloak.tls=true"
                - "traefik.http.routers.astra50-keycloak.tls.certresolver=leresolver"
                - "traefik.http.services.astra50-keycloak-service.loadbalancer.server.port=8080"
                - "traefik.http.services.astra50-keycloak-service.loadbalancer.server.scheme=http"

    nextcloud:
        image: nextcloud:22.1.0-apache
        entrypoint: /bin/sh
        command: -c "apt-get update && apt-get install -y imagemagick && rm -rf /var/lib/apt/lists/*; /entrypoint.sh apache2-foreground"
        environment:
            POSTGRES_DB: nextcloud
            POSTGRES_USER: db
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            REDIS_HOST: redis
            NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
            NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
            NEXTCLOUD_TRUSTED_DOMAINS: cloud.astra50.ru
            SMTP_HOST: ${SMTP_HOST}
            SMTP_SECURE: ssl
            SMTP_NAME: ${SMTP_USERNAME}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            MAIL_FROM_ADDRESS: cloud@astra50.ru
            OBJECTSTORE_S3_HOST: minio
            OBJECTSTORE_S3_BUCKET: nextcloud
            OBJECTSTORE_S3_KEY: ${MINIO_ACCESS_KEY}
            OBJECTSTORE_S3_SECRET: ${MINIO_SECRET_KEY}
            OBJECTSTORE_S3_PORT: 9000
            OBJECTSTORE_S3_SSL: 'false'
            OBJECTSTORE_S3_USEPATH_STYLE: 'true'
            OVERWRITEPROTOCOL: https
        volumes:
            -   type: bind
                source: /opt/astra50/nextcloud/data
                target: /var/www/html
        networks:
            - default
            - traefik
        deploy:
            update_config:
                order: start-first
                failure_action: rollback
                parallelism: 1
                delay: 5s
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.astra50-nextcloud.rule=Host(`cloud.astra50.ru`)"
                - "traefik.http.routers.astra50-nextcloud.entrypoints=websecure"
                - "traefik.http.routers.astra50-nextcloud.tls=true"
                - "traefik.http.routers.astra50-nextcloud.tls.certresolver=leresolver"
                - "traefik.http.routers.astra50-nextcloud.middlewares=nextcloud-redirect-dav,nextcloud-secure-headers"
                - "traefik.http.services.astra50-nextcloud-service.loadbalancer.server.port=80"
                - "traefik.http.services.astra50-nextcloud-service.loadbalancer.server.scheme=http"
                - "traefik.http.middlewares.nextcloud-redirect-dav.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
                - "traefik.http.middlewares.nextcloud-redirect-dav.redirectregex.replacement=https://$${1}/remote.php/dav/"
                - "traefik.http.middlewares.nextcloud-redirect-dav.redirectregex.permanent=true"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.accessControlMaxAge=100"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.sslRedirect=true"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.stsSeconds=63072000"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.stsIncludeSubdomains=true"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.stsPreload=true"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.forceSTSHeader=true"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.customFrameOptionsValue=SAMEORIGIN"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.contentTypeNosniff=true"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.browserXssFilter=true"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.referrerPolicy=no-referrer"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.featurePolicy=camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.customResponseHeaders.X-Robots-Tag=none"
                - "traefik.http.middlewares.nextcloud-secure-headers.headers.customResponseHeaders.server=''"

    onlyoffice:
        image: onlyoffice/documentserver:6.4.0.121
        environment:
            ONLYOFFICE_HTTPS_HSTS_ENABLED: 'false'
        networks:
            - default
            - traefik
        deploy:
            update_config:
                order: stop-first
                failure_action: rollback
                parallelism: 1
                delay: 5s
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.astra50-onlyoffice.rule=Host(`office.astra50.ru`)"
                - "traefik.http.routers.astra50-onlyoffice.entrypoints=websecure"
                - "traefik.http.routers.astra50-onlyoffice.tls=true"
                - "traefik.http.routers.astra50-onlyoffice.tls.certresolver=leresolver"
                - "traefik.http.services.astra50-onlyoffice-service.loadbalancer.server.port=80"
                - "traefik.http.services.astra50-onlyoffice-service.loadbalancer.server.scheme=http"

    redis:
        image: redis:6.2.5-alpine
        volumes:
            -   type: bind
                source: /opt/astra50/redis/data
                target: /data
        deploy:
            update_config:
                order: stop-first

    minio:
        image: minio/minio:RELEASE.2021-08-25T00-41-18Z
        command:
            - minio
            - server
            - /data
            - --console-address=:9001
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        volumes:
            -   type: bind
                source: /opt/astra50/minio/data
                target: /data
        networks:
            - default
            - traefik
        deploy:
            update_config:
                order: stop-first
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.astra50-minio.rule=Host(`minio.astra50.ru`)"
                - "traefik.http.routers.astra50-minio.entrypoints=websecure"
                - "traefik.http.routers.astra50-minio.tls=true"
                - "traefik.http.routers.astra50-minio.tls.certresolver=leresolver"
                - "traefik.http.services.astra50-minio-service.loadbalancer.server.port=9001"
                - "traefik.http.services.astra50-minio-service.loadbalancer.server.scheme=http"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
            interval: 30s
            timeout: 20s
            retries: 3

networks:
    default:
        driver: overlay
        name: astra50
    traefik:
        external: true
        name: traefik
