version: '3.7'

services:
    react-admin:
        image: node:14.18.0-alpine3.12
        extra_hosts:
            - crm.astra50.local:0.0.0.0
        labels:
            ru.grachevko.dhu: 'crm.astra50.local'
        command: yarn start
        environment:
            HOST: crm.astra50.local
            PORT: 80
        volumes:
            - ./:/app
        working_dir: /app
