global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'astra50'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    dns_sd_configs:
      - names:
          - 'tasks.minio.astra50'
        type: 'A'
        port: 9000
