-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."member_payment" add column "is_regular" boolean
--  not null default 'False';
